services:
  app:
    image: "gps_listener_image_arm64:latest"
    network_mode: "host"
    volumes:
      - "/opt/payload_credentials:/creds"
    devices:
      - /dev/leica1:/dev/leica
    restart: unless-stopped
    command:
      [
        "--name",
        "Leica GA03",
        "--payload-tform-gps",
        "0",
        "0",
        "0.032",
        "1",
        "0",
        "0",
        "0",
        "--payload-credentials-file",
        "/creds/payload_guid_and_secret",
        "192.168.50.3",
        "--register-payload",
        "--mass",
        ".671",
        "--description",
        "Leica GA03 for GPS integration",
        "--position",
        "-.520",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
        "--position-of-mass",
        "-.083",
        "0",
        ".02595",
        "--bounding-box",
        "-.083",
        "0",
        ".02595",
        "1",
        "0",
        "0",
        "0",
        ".065",
        ".053",
        "0.03844",
        "--gps-credentials-file",
        "/creds/leica-gps-payload-credentials.txt",
        "--version",
        "1",
        "0",
        "0",
        "serial",
        "--serial-device",
        "/dev/leica",
      ]
